### ISSUE TITLE
Client is kinda clunky for accessing multiple repos

### ISSUE THREAD

**Issue by vincentwoo** [joyent/node-docker-registry-client#3]
As it stands, you have to make a new client or much with private internals to request data on more than one repo. Could we add an option for changing the repo? Perhaps as a parameter to the various functions or as a configurable option via a method?

**Comment by trentm** [comment]
@vincentwoo If anything I'd prefer to wait for a bit (perhaps a couple/few weeks) before many changes here. I have a number of uncommited changes working towards supporting the v2 api as well.

Also, FWIW, and if I recall correctly I've been trying to follow similar objects/methods/handling as is done in docker.git's registry client.
