### ISSUE TITLE
Fails install on OSX node4-lts

### ISSUE THREAD

**Issue by ProTip** [joyent/node-docker-registry-client#9]
Hello,

You appear to be using an old revision of joyent/node-restify that has an optional dependency of `"dtrace-provider": "^0.3.1"`. This version fails to install on OSX node4-lts. I believe they have fixed this in `^0.4.0`. Both the latest(and package.json) bunyan as well as joyent/node-restify have dependencies on the fixed dtrace-provider.

**Comment by trentm** [comment]
Thanks. This should be fixed in v3.2.0 with this change: "DOCKER-940: Update to support node v4 without build errors." (commit 2adc468e202634d7c7c35937e19f4a9d61ac71bb)
